name: Run Tests
on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
            version: 9.13.2
            run_install: true

      - name: Run tests
        run: pnpm test