name: Run Tests
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Run tests
        run: pnpm test